title: Luigi Beta
description:
markdown: kramdown

collections:
  posts:
    permalink: /blog/:slug/
    layout: post

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
